**Aritmetica**


In [ ]:
"Prueba de operaciones básicas aritméticas en Python"

a = 45
b = 21

print("A + B es: ", a + b)
print(f"A - B es: {a - b}")
print(f"A * B es: {a * b}")
print(f"A / B es: {a / b:#.2f}")

A + B es:  66
A - B es: 24
A * B es: 945
A / B es: 2.14


In [33]:
print("=== Módulo ===")

respuesta = input("¿Desea probar el módulo? (s/n): ").lower()

while respuesta == "s":

    a = int(input("Ingresa un número: "))

    if a % 2 == 0:
        print(f"{a} es par")
    else:
        print(f"{a} es impar")

    respuesta = input("¿Desea probar otro número? (s/n): ").lower()

print("No se probará el módulo.")

=== Módulo ===
21 es impar
65 es impar
No se probará el módulo.


**Geometría**


In [23]:
"Calcular area de un cuadrado"
# cuadrado
lado = float(input("Ingresa el valor del lado del cuadrado en cm: "))

area = lado * lado
print(f"El área del cuadrado es: {area} cm²")
print(f"El perimetro del cuadrado es {lado*4} cm")

El área del cuadrado es: 25.0 cm²
El perimetro del cuadrado es 20.0 cm


circulo

In [ ]:
import math as mat

radio = float(input("Ingresa el valor del radio de un circulo en cm: "))

unidad_de_medida = "cm"

perimetro = 2 * (mat.pi) * radio   
#FUNCION PARA IMPRIMIR EL PERIMETRO Y AREA DEL CIRCULO
def __str__():
    return f"El perímetro del círculo es: {perimetro:.2f} {unidad_de_medida}\nEl área del círculo es: {mat.pi * (radio ** 2):.2f} {unidad_de_medida}²"

print(__str__())

El perímetro del círculo es: 31.42 cm
El área del círculo es: 78.54 cm²


**Algebra**

In [1]:
import sys

print(sys.executable)
print(sys.version)

d:\MisDesarrollos\SciTools\.venv\Scripts\python.exe
3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]


In [2]:
## Matrices
import numpy as np

In [4]:
matriz = np.array([[1,2,2],[3,5,4],[6,5,8]])

for linea in matriz:
    print(linea)

[1 2 2]
[3 5 4]
[6 5 8]


In [30]:
# Suma de matrices
a = np.array([[12, 23, 33], [40, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 52, 4], [3, 21, 10]])

c = a + b

print("La suma de la matriz a y b da la matriz c")

#Suma de matrices
print("Matriz: c\n",c)

# Transpuesta de la matriz c
print(f"La transpuesta de la matriz c es:\n{c.T}")

#deteminante de la matriz c
determinante = int(round(np.linalg.det(c)))
print(f"El determinante de la matriz c es: {determinante}")

La suma de la matriz a y b da la matriz c
Matriz: c
 [[21 31 40]
 [46 57 10]
 [10 29 19]]
La transpuesta de la matriz c es:
[[21 46 10]
 [31 57 29]
 [40 10 19]]
El determinante de la matriz c es: 23219
